# Example that will create a CronJob in Kubernetes
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
 name: job-cleaner
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
       template:
         metadata:
           name: job-cleaner
         spec:
           containers:
           - name: job-cleaner
             image: jobliterator:0.1
             command: ["/jobliterator"]
             args: ["-in-cluster","-days","10","-f"]
             imagePullPolicy: Always
           restartPolicy: Never

